server {
    listen 80;

    root /usr/share/nginx/html;

    location = / {
        return 302 es/index.html;
    }

    location /es/ {
        try_files $uri $uri/ /es/index.html;
    }

    location /en/ {
        try_files $uri $uri/ /en/index.html;
    }
}