name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: npm

      - name: Instalar dependencias
        run: npm ci

      - name: Compilar Angular
        run: npm run build

      - name: Construir imagen Docker
        run: docker build -t portfolio-angular .
      

